name: Docs CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    paths:
      - 'docs/**'
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v2

      - name: Generate docs
        run: |
          python3 docs/scripts/gen.py spectrum/ docs/source/reference/spectrum
          python3 docs/scripts/gen.py engine/ docs/source/reference/prism
          pip install sphinx-lua-ls

      - name: Build docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html

